/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentRentalsRouteImport } from './routes/tent-rentals'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RecommenderRouteImport } from './routes/recommender'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiTentPlannerRouteImport } from './routes/ai-tent-planner'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSchedulerRouteImport } from './routes/admin.scheduler'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminQuoteRequestsRouteImport } from './routes/admin.quote-requests'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminDataImportRouteImport } from './routes/admin.data-import'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AccountIdRouteImport } from './routes/account.$id'
import { Route as AdminQuoteRequestsIdRouteImport } from './routes/admin.quote-requests.$id'
import { Route as AdminInventoryIdRouteImport } from './routes/admin.inventory.$id'
import { Route as ApiPublicHooksSpreadsheetSyncRouteImport } from './routes/api/public/hooks/spreadsheet-sync'
import { Route as AdminQuotesIdPreviewRouteImport } from './routes/admin.quotes.$id.preview'
import { Route as AdminQuotesIdJobSheetRouteImport } from './routes/admin.quotes.$id.job-sheet'
import { Route as AdminQuotesIdEditRouteImport } from './routes/admin.quotes.$id.edit'

const TentRentalsRoute = TentRentalsRouteImport.update({
  id: '/tent-rentals',
  path: '/tent-rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommenderRoute = RecommenderRouteImport.update({
  id: '/recommender',
  path: '/recommender',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTentPlannerRoute = AiTentPlannerRouteImport.update({
  id: '/ai-tent-planner',
  path: '/ai-tent-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulerRoute = AdminSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuoteRequestsRoute = AdminQuoteRequestsRouteImport.update({
  id: '/quote-requests',
  path: '/quote-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataImportRoute = AdminDataImportRouteImport.update({
  id: '/data-import',
  path: '/data-import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIdRoute = AccountIdRouteImport.update({
  id: '/account/$id',
  path: '/account/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuoteRequestsIdRoute = AdminQuoteRequestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminQuoteRequestsRoute,
} as any)
const AdminInventoryIdRoute = AdminInventoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInventoryRoute,
} as any)
const ApiPublicHooksSpreadsheetSyncRoute =
  ApiPublicHooksSpreadsheetSyncRouteImport.update({
    id: '/api/public/hooks/spreadsheet-sync',
    path: '/api/public/hooks/spreadsheet-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminQuotesIdPreviewRoute = AdminQuotesIdPreviewRouteImport.update({
  id: '/$id/preview',
  path: '/$id/preview',
  getParentRoute: () => AdminQuotesRoute,
} as any)
const AdminQuotesIdJobSheetRoute = AdminQuotesIdJobSheetRouteImport.update({
  id: '/$id/job-sheet',
  path: '/$id/job-sheet',
  getParentRoute: () => AdminQuotesRoute,
} as any)
const AdminQuotesIdEditRoute = AdminQuotesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminQuotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-tent-planner': typeof AiTentPlannerRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/recommender': typeof RecommenderRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tent-rentals': typeof TentRentalsRoute
  '/account/$id': typeof AccountIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data-import': typeof AdminDataImportRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/quote-requests': typeof AdminQuoteRequestsRouteWithChildren
  '/admin/quotes': typeof AdminQuotesRouteWithChildren
  '/admin/scheduler': typeof AdminSchedulerRoute
  '/admin/staff': typeof AdminStaffRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/inventory/$id': typeof AdminInventoryIdRoute
  '/admin/quote-requests/$id': typeof AdminQuoteRequestsIdRoute
  '/admin/quotes/$id/edit': typeof AdminQuotesIdEditRoute
  '/admin/quotes/$id/job-sheet': typeof AdminQuotesIdJobSheetRoute
  '/admin/quotes/$id/preview': typeof AdminQuotesIdPreviewRoute
  '/api/public/hooks/spreadsheet-sync': typeof ApiPublicHooksSpreadsheetSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-tent-planner': typeof AiTentPlannerRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/recommender': typeof RecommenderRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tent-rentals': typeof TentRentalsRoute
  '/account/$id': typeof AccountIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data-import': typeof AdminDataImportRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/quote-requests': typeof AdminQuoteRequestsRouteWithChildren
  '/admin/quotes': typeof AdminQuotesRouteWithChildren
  '/admin/scheduler': typeof AdminSchedulerRoute
  '/admin/staff': typeof AdminStaffRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/inventory/$id': typeof AdminInventoryIdRoute
  '/admin/quote-requests/$id': typeof AdminQuoteRequestsIdRoute
  '/admin/quotes/$id/edit': typeof AdminQuotesIdEditRoute
  '/admin/quotes/$id/job-sheet': typeof AdminQuotesIdJobSheetRoute
  '/admin/quotes/$id/preview': typeof AdminQuotesIdPreviewRoute
  '/api/public/hooks/spreadsheet-sync': typeof ApiPublicHooksSpreadsheetSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ai-tent-planner': typeof AiTentPlannerRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/inventory': typeof InventoryRoute
  '/login': typeof LoginRoute
  '/recommender': typeof RecommenderRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tent-rentals': typeof TentRentalsRoute
  '/account/$id': typeof AccountIdRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/data-import': typeof AdminDataImportRoute
  '/admin/inventory': typeof AdminInventoryRouteWithChildren
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/quote-requests': typeof AdminQuoteRequestsRouteWithChildren
  '/admin/quotes': typeof AdminQuotesRouteWithChildren
  '/admin/scheduler': typeof AdminSchedulerRoute
  '/admin/staff': typeof AdminStaffRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/inventory/$id': typeof AdminInventoryIdRoute
  '/admin/quote-requests/$id': typeof AdminQuoteRequestsIdRoute
  '/admin/quotes/$id/edit': typeof AdminQuotesIdEditRoute
  '/admin/quotes/$id/job-sheet': typeof AdminQuotesIdJobSheetRoute
  '/admin/quotes/$id/preview': typeof AdminQuotesIdPreviewRoute
  '/api/public/hooks/spreadsheet-sync': typeof ApiPublicHooksSpreadsheetSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai-tent-planner'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/inventory'
    | '/login'
    | '/recommender'
    | '/services'
    | '/sitemap.xml'
    | '/tent-rentals'
    | '/account/$id'
    | '/admin/dashboard'
    | '/admin/data-import'
    | '/admin/inventory'
    | '/admin/pricing'
    | '/admin/quote-requests'
    | '/admin/quotes'
    | '/admin/scheduler'
    | '/admin/staff'
    | '/account/'
    | '/admin/'
    | '/admin/inventory/$id'
    | '/admin/quote-requests/$id'
    | '/admin/quotes/$id/edit'
    | '/admin/quotes/$id/job-sheet'
    | '/admin/quotes/$id/preview'
    | '/api/public/hooks/spreadsheet-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-tent-planner'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/inventory'
    | '/login'
    | '/recommender'
    | '/services'
    | '/sitemap.xml'
    | '/tent-rentals'
    | '/account/$id'
    | '/admin/dashboard'
    | '/admin/data-import'
    | '/admin/inventory'
    | '/admin/pricing'
    | '/admin/quote-requests'
    | '/admin/quotes'
    | '/admin/scheduler'
    | '/admin/staff'
    | '/account'
    | '/admin'
    | '/admin/inventory/$id'
    | '/admin/quote-requests/$id'
    | '/admin/quotes/$id/edit'
    | '/admin/quotes/$id/job-sheet'
    | '/admin/quotes/$id/preview'
    | '/api/public/hooks/spreadsheet-sync'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai-tent-planner'
    | '/contact'
    | '/events'
    | '/gallery'
    | '/inventory'
    | '/login'
    | '/recommender'
    | '/services'
    | '/sitemap.xml'
    | '/tent-rentals'
    | '/account/$id'
    | '/admin/dashboard'
    | '/admin/data-import'
    | '/admin/inventory'
    | '/admin/pricing'
    | '/admin/quote-requests'
    | '/admin/quotes'
    | '/admin/scheduler'
    | '/admin/staff'
    | '/account/'
    | '/admin/'
    | '/admin/inventory/$id'
    | '/admin/quote-requests/$id'
    | '/admin/quotes/$id/edit'
    | '/admin/quotes/$id/job-sheet'
    | '/admin/quotes/$id/preview'
    | '/api/public/hooks/spreadsheet-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AiTentPlannerRoute: typeof AiTentPlannerRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  InventoryRoute: typeof InventoryRoute
  LoginRoute: typeof LoginRoute
  RecommenderRoute: typeof RecommenderRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TentRentalsRoute: typeof TentRentalsRoute
  AccountIdRoute: typeof AccountIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  ApiPublicHooksSpreadsheetSyncRoute: typeof ApiPublicHooksSpreadsheetSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tent-rentals': {
      id: '/tent-rentals'
      path: '/tent-rentals'
      fullPath: '/tent-rentals'
      preLoaderRoute: typeof TentRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommender': {
      id: '/recommender'
      path: '/recommender'
      fullPath: '/recommender'
      preLoaderRoute: typeof RecommenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-tent-planner': {
      id: '/ai-tent-planner'
      path: '/ai-tent-planner'
      fullPath: '/ai-tent-planner'
      preLoaderRoute: typeof AiTentPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scheduler': {
      id: '/admin/scheduler'
      path: '/scheduler'
      fullPath: '/admin/scheduler'
      preLoaderRoute: typeof AdminSchedulerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quote-requests': {
      id: '/admin/quote-requests'
      path: '/quote-requests'
      fullPath: '/admin/quote-requests'
      preLoaderRoute: typeof AdminQuoteRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data-import': {
      id: '/admin/data-import'
      path: '/data-import'
      fullPath: '/admin/data-import'
      preLoaderRoute: typeof AdminDataImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/$id': {
      id: '/account/$id'
      path: '/account/$id'
      fullPath: '/account/$id'
      preLoaderRoute: typeof AccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quote-requests/$id': {
      id: '/admin/quote-requests/$id'
      path: '/$id'
      fullPath: '/admin/quote-requests/$id'
      preLoaderRoute: typeof AdminQuoteRequestsIdRouteImport
      parentRoute: typeof AdminQuoteRequestsRoute
    }
    '/admin/inventory/$id': {
      id: '/admin/inventory/$id'
      path: '/$id'
      fullPath: '/admin/inventory/$id'
      preLoaderRoute: typeof AdminInventoryIdRouteImport
      parentRoute: typeof AdminInventoryRoute
    }
    '/api/public/hooks/spreadsheet-sync': {
      id: '/api/public/hooks/spreadsheet-sync'
      path: '/api/public/hooks/spreadsheet-sync'
      fullPath: '/api/public/hooks/spreadsheet-sync'
      preLoaderRoute: typeof ApiPublicHooksSpreadsheetSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotes/$id/preview': {
      id: '/admin/quotes/$id/preview'
      path: '/$id/preview'
      fullPath: '/admin/quotes/$id/preview'
      preLoaderRoute: typeof AdminQuotesIdPreviewRouteImport
      parentRoute: typeof AdminQuotesRoute
    }
    '/admin/quotes/$id/job-sheet': {
      id: '/admin/quotes/$id/job-sheet'
      path: '/$id/job-sheet'
      fullPath: '/admin/quotes/$id/job-sheet'
      preLoaderRoute: typeof AdminQuotesIdJobSheetRouteImport
      parentRoute: typeof AdminQuotesRoute
    }
    '/admin/quotes/$id/edit': {
      id: '/admin/quotes/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/quotes/$id/edit'
      preLoaderRoute: typeof AdminQuotesIdEditRouteImport
      parentRoute: typeof AdminQuotesRoute
    }
  }
}

interface AdminInventoryRouteChildren {
  AdminInventoryIdRoute: typeof AdminInventoryIdRoute
}

const AdminInventoryRouteChildren: AdminInventoryRouteChildren = {
  AdminInventoryIdRoute: AdminInventoryIdRoute,
}

const AdminInventoryRouteWithChildren = AdminInventoryRoute._addFileChildren(
  AdminInventoryRouteChildren,
)

interface AdminQuoteRequestsRouteChildren {
  AdminQuoteRequestsIdRoute: typeof AdminQuoteRequestsIdRoute
}

const AdminQuoteRequestsRouteChildren: AdminQuoteRequestsRouteChildren = {
  AdminQuoteRequestsIdRoute: AdminQuoteRequestsIdRoute,
}

const AdminQuoteRequestsRouteWithChildren =
  AdminQuoteRequestsRoute._addFileChildren(AdminQuoteRequestsRouteChildren)

interface AdminQuotesRouteChildren {
  AdminQuotesIdEditRoute: typeof AdminQuotesIdEditRoute
  AdminQuotesIdJobSheetRoute: typeof AdminQuotesIdJobSheetRoute
  AdminQuotesIdPreviewRoute: typeof AdminQuotesIdPreviewRoute
}

const AdminQuotesRouteChildren: AdminQuotesRouteChildren = {
  AdminQuotesIdEditRoute: AdminQuotesIdEditRoute,
  AdminQuotesIdJobSheetRoute: AdminQuotesIdJobSheetRoute,
  AdminQuotesIdPreviewRoute: AdminQuotesIdPreviewRoute,
}

const AdminQuotesRouteWithChildren = AdminQuotesRoute._addFileChildren(
  AdminQuotesRouteChildren,
)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDataImportRoute: typeof AdminDataImportRoute
  AdminInventoryRoute: typeof AdminInventoryRouteWithChildren
  AdminPricingRoute: typeof AdminPricingRoute
  AdminQuoteRequestsRoute: typeof AdminQuoteRequestsRouteWithChildren
  AdminQuotesRoute: typeof AdminQuotesRouteWithChildren
  AdminSchedulerRoute: typeof AdminSchedulerRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDataImportRoute: AdminDataImportRoute,
  AdminInventoryRoute: AdminInventoryRouteWithChildren,
  AdminPricingRoute: AdminPricingRoute,
  AdminQuoteRequestsRoute: AdminQuoteRequestsRouteWithChildren,
  AdminQuotesRoute: AdminQuotesRouteWithChildren,
  AdminSchedulerRoute: AdminSchedulerRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AiTentPlannerRoute: AiTentPlannerRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  InventoryRoute: InventoryRoute,
  LoginRoute: LoginRoute,
  RecommenderRoute: RecommenderRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TentRentalsRoute: TentRentalsRoute,
  AccountIdRoute: AccountIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  ApiPublicHooksSpreadsheetSyncRoute: ApiPublicHooksSpreadsheetSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
